# Mac OS X (https://github.com/travis-ci-tester/toolchain-table)

language:
    - objective-c

env:
    - TOOLCHAIN=default TEST="--test" CONFIG=Release
    - TOOLCHAIN=default TEST="--test" CONFIG=Debug
    - TOOLCHAIN=libcxx TEST="--test" CONFIG=Release
    - TOOLCHAIN=libcxx TEST="--test" CONFIG=Debug
    - TOOLCHAIN=clang_libstdcxx TEST="--test" CONFIG=Release
    - TOOLCHAIN=clang_libstdcxx TEST="--test" CONFIG=Debug
    - TOOLCHAIN=xcode TEST="--test" CONFIG=Release
    - TOOLCHAIN=xcode TEST="--test" CONFIG=Debug
    - TOOLCHAIN=gcc TEST="--test" CONFIG=Release
    - TOOLCHAIN=gcc TEST="--test" CONFIG=Debug
    - TOOLCHAIN=ios-nocodesign EXTRA="--iossim" CONFIG=Release
    - TOOLCHAIN=ios-nocodesign EXTRA="--iossim" CONFIG=Debug
        # Extra cmake modules needed for iOS testing:
        # * https://github.com/ruslo/sugar/tree/master/cmake/core#sugar_add_ios_gtest
    - TOOLCHAIN=analyze TEST="--test" CONFIG=Release
    - TOOLCHAIN=analyze TEST="--test" CONFIG=Debug

install:
    - brew install cmake
    - brew install python3
    # install cmake toolchains and script
    - POLLY_VERSION="0.4.4"
    - wget "https://github.com/ruslo/polly/archive/v${POLLY_VERSION}.tar.gz"
    - tar xf "v${POLLY_VERSION}.tar.gz"
    - export POLLY_ROOT="`pwd`/polly-${POLLY_VERSION}"
    - export PATH="${POLLY_ROOT}/bin:${PATH}"
    # -- end
    # install cmake
    - CMAKE_VERSION="3.0.0-ios-universal"
    - wget "https://github.com/ruslo/CMake/archive/v${CMAKE_VERSION}.tar.gz"
    - openssl sha1 "v${CMAKE_VERSION}.tar.gz"
    - tar xf "v${CMAKE_VERSION}.tar.gz"
    - cd "CMake-${CMAKE_VERSION}"
    -   build.py --install --toolchain default --config Release --fwd "CMAKE_USE_SYSTEM_CURL=YES"
    -   export PATH="`pwd`/_install/default/bin:${PATH}"
    - cd ..
    # -- end
    # verify installed cmake
    - which cmake
    - cmake --version
    # -- end
    # https://github.com/ruslo/polly/wiki/Toolchain-list#ios-nocodesign
    - export XCODE_XCCONFIG_FILE="${POLLY_ROOT}/scripts/NoCodeSign.xcconfig"
    # -- end

script:
    - build.py --toolchain ${TOOLCHAIN} --config ${CONFIG} --verbose ${TEST} ${EXTRA}
